language: cpp
dist: trusty
sudo: false

script:
  - set -e
# clone parent repo and link this repo as plugin to it
  - this_repo=$(pwd)
  - mkdir ../farm
  - git clone --depth=1 https://github.com/AndriiNikitin/mariadb-environs ../farm
  - rm -r ../farm/_plugin/xtrabackup
  - ln -s $this_repo ../farm/_plugin/xtrabackup
# now trigger build and test
  - cd ../farm
  # run example test to make sure prereqiusites are met
  - ./runsuite.sh _plugin/example/_matrix/echoN.lst
  - _plugin/xtrabackup/_test/deploy_and_test.sh
